import { Output, randomPassword, Services } from "~templates-utils";
import { Input } from "./meta";

export function generate(input: Input): Output {
  const services: Services = [];
  const databasePassword = randomPassword();

  services.push({
    type: "app",
    data: {
      serviceName: input.appServiceName,
      env: [
        `APP_ENV=production`,
        `APP_DEBUG=false`,
        `APP_KEY=base64:3ilviXqB9u6DX1NRcyWGJ+sjySF+H18CPDGb3+IVwMQ=`,
        `APP_URL=https://$(PRIMARY_DOMAIN)`,
        `APP_TIMEZONE='UTC'`,
        `APP_LOCALE='en-US'`,
        `MAX_RESULTS=500`,
        `PRIVATE_FILESYSTEM_DISK=local`,
        `PUBLIC_FILESYSTEM_DISK=local_public`,
        `DB_CONNECTION=mysql`,
        `DB_HOST=$(PROJECT_NAME)_${input.appServiceName}-db`,
        `DB_PORT=3306`,
        `DB_DATABASE=$(PROJECT_NAME)`,
        `DB_USERNAME=mariadb`,
        `DB_PASSWORD=${databasePassword}`,
        `DB_PREFIX=null`,
        `DB_DUMP_PATH='/usr/bin'`,
        `DB_CHARSET=utf8mb4`,
        `DB_COLLATION=utf8mb4_unicode_ci`,
        `DB_SANITIZE_BY_DEFAULT=false`,
        `DB_SSL=false`,
        `DB_SSL_IS_PAAS=false`,
        `DB_SSL_KEY_PATH=null`,
        `DB_SSL_CERT_PATH=null`,
        `DB_SSL_CA_PATH=null`,
        `DB_SSL_CIPHER=null`,
        `DB_SSL_VERIFY_SERVER=null`,
        `MAIL_MAILER=smtp`,
        `MAIL_HOST=${input.smtpHost}`,
        `MAIL_PORT=${input.smtpPort}`,
        `MAIL_USERNAME=${input.smtpUsername}`,
        `MAIL_PASSWORD=${input.smtpPassword}`,
        `MAIL_FROM_ADDR=${input.smtpFromAddress}`,
        `MAIL_FROM_NAME='${input.smtpFromName}`,
        `MAIL_REPLYTO_ADDR=${input.smtpReplyToEmail}`,
        `MAIL_REPLYTO_NAME='${input.smtpReplyToName}`,
        `MAIL_AUTO_EMBED_METHOD='attachment'`,
        `MAIL_TLS_VERIFY_PEER=true`,
        `IMAGE_LIB=gd`,
        `MAIL_BACKUP_NOTIFICATION_DRIVER=null`,
        `MAIL_BACKUP_NOTIFICATION_ADDRESS=null`,
        `BACKUP_ENV=true`,
        `ALLOW_BACKUP_DELETE=false`,
        `ALLOW_DATA_PURGE=false`,
        `SESSION_DRIVER=file`,
        `SESSION_LIFETIME=12000`,
        `EXPIRE_ON_CLOSE=false`,
        `ENCRYPT=false`,
        `COOKIE_NAME=snipeit_session`,
        `PASSPORT_COOKIE_NAME='snipeit_passport_token'`,
        `COOKIE_DOMAIN=null`,
        `SECURE_COOKIES=false`,
        `API_TOKEN_EXPIRATION_YEARS=15`,
        `BS_TABLE_STORAGE=cookieStorage`,
        `BS_TABLE_DEEPLINK=true`,
        `APP_TRUSTED_PROXIES=192.168.1.1,10.0.0.1`,
        `ALLOW_IFRAMING=false`,
        `REFERRER_POLICY=same-origin`,
        `ENABLE_CSP=false`,
        `ADDITIONAL_CSP_URLS=null`,
        `CORS_ALLOWED_ORIGINS=null`,
        `ENABLE_HSTS=false`,
        `CACHE_DRIVER=file`,
        `QUEUE_DRIVER=sync`,
        `CACHE_PREFIX=snipeit`,
        `REDIS_HOST=null`,
        `REDIS_PASSWORD=null`,
        `REDIS_PORT=null`,
        `MEMCACHED_HOST=null`,
        `MEMCACHED_PORT=null`,
        `PUBLIC_AWS_SECRET_ACCESS_KEY=null`,
        `PUBLIC_AWS_ACCESS_KEY_ID=null`,
        `PUBLIC_AWS_DEFAULT_REGION=null`,
        `PUBLIC_AWS_BUCKET=null`,
        `PUBLIC_AWS_URL=null`,
        `PUBLIC_AWS_BUCKET_ROOT=null`,
        `PRIVATE_AWS_ACCESS_KEY_ID=null`,
        `PRIVATE_AWS_SECRET_ACCESS_KEY=null`,
        `PRIVATE_AWS_DEFAULT_REGION=null`,
        `PRIVATE_AWS_BUCKET=null`,
        `PRIVATE_AWS_URL=null`,
        `PRIVATE_AWS_BUCKET_ROOT=null`,
        `AWS_ACCESS_KEY_ID=null`,
        `AWS_SECRET_ACCESS_KEY=null`,
        `AWS_DEFAULT_REGION=null`,
        `LOGIN_MAX_ATTEMPTS=5`,
        `LOGIN_LOCKOUT_DURATION=60`,
        `LOGIN_AUTOCOMPLETE=false`,
        `RESET_PASSWORD_LINK_EXPIRES=15`,
        `PASSWORD_CONFIRM_TIMEOUT=10800`,
        `PASSWORD_RESET_MAX_ATTEMPTS_PER_MIN=50`,
        `LOG_CHANNEL=single`,
        `LOG_MAX_DAYS=10`,
        `APP_LOCKED=false`,
        `APP_CIPHER=AES-256-CBC`,
        `APP_FORCE_TLS=false`,
        `APP_ALLOW_INSECURE_HOSTS=false`,
        `GOOGLE_MAPS_API=`,
        `LDAP_MEM_LIM=500M`,
        `LDAP_TIME_LIM=600`,
        `IMPORT_TIME_LIMIT=600`,
        `IMPORT_MEMORY_LIMIT=500M`,
        `REPORT_TIME_LIMIT=12000`,
        `REQUIRE_SAML=false`,
        `API_THROTTLE_PER_MINUTE=120`,
        `CSV_ESCAPE_FORMULAS=true`,
        `LIVEWIRE_URL_PREFIX=null`,
        `HASHING_DRIVER='bcrypt'`,
        `BCRYPT_ROUNDS=10`,
        `ARGON_MEMORY=1024`,
        `ARGON_THREADS=2`,
        `ARGON_TIME=2`,
        `SCIM_TRACE=false`,
        `SCIM_STANDARDS_COMPLIANCE=false`,
      ].join("\n"),
      source: {
        type: "image",
        image: input.appServiceImage,
      },
      domains: [
        {
          host: "$(EASYPANEL_DOMAIN)",
          port: 80,
        },
      ],
      mounts: [
        {
          type: "volume",
          name: "storage",
          mountPath: "/var/lib/snipeit",
        },
      ],
    },
  });

  services.push({
    type: "mariadb",
    data: {
      serviceName: `${input.appServiceName}-db`,
      password: databasePassword,
      image: "mariadb:11.5.2",
    },
  });

  return { services };
}
