// Generated using "yarn build-templates"

import { meta as meta_ackee } from "./ackee/meta";
import { generate as generate_ackee } from "./ackee";
import { meta as meta_adminer } from "./adminer/meta";
import { generate as generate_adminer } from "./adminer";
import { meta as meta_anonupload } from "./anonupload/meta";
import { generate as generate_anonupload } from "./anonupload";
import { meta as meta_appsmith } from "./appsmith/meta";
import { generate as generate_appsmith } from "./appsmith";
import { meta as meta_baserow } from "./baserow/meta";
import { generate as generate_baserow } from "./baserow";
import { meta as meta_bookstack } from "./bookstack/meta";
import { generate as generate_bookstack } from "./bookstack";
import { meta as meta_budibase } from "./budibase/meta";
import { generate as generate_budibase } from "./budibase";
import { meta as meta_changedetection } from "./changedetection/meta";
import { generate as generate_changedetection } from "./changedetection";
import { meta as meta_dashy } from "./dashy/meta";
import { generate as generate_dashy } from "./dashy";
import { meta as meta_directus } from "./directus/meta";
import { generate as generate_directus } from "./directus";
import { meta as meta_domainmod } from "./domainmod/meta";
import { generate as generate_domainmod } from "./domainmod";
import { meta as meta_drone_runner } from "./drone-runner/meta";
import { generate as generate_drone_runner } from "./drone-runner";
import { meta as meta_drone } from "./drone/meta";
import { generate as generate_drone } from "./drone";
import { meta as meta_duplicati } from "./duplicati/meta";
import { generate as generate_duplicati } from "./duplicati";
import { meta as meta_element } from "./element/meta";
import { generate as generate_element } from "./element";
import { meta as meta_emby } from "./emby/meta";
import { generate as generate_emby } from "./emby";
import { meta as meta_fider } from "./fider/meta";
import { generate as generate_fider } from "./fider";
import { meta as meta_filebrowser } from "./filebrowser/meta";
import { generate as generate_filebrowser } from "./filebrowser";
import { meta as meta_filezilla } from "./filezilla/meta";
import { generate as generate_filezilla } from "./filezilla";
import { meta as meta_firefox } from "./firefox/meta";
import { generate as generate_firefox } from "./firefox";
import { meta as meta_flame } from "./flame/meta";
import { generate as generate_flame } from "./flame";
import { meta as meta_flarum } from "./flarum/meta";
import { generate as generate_flarum } from "./flarum";
import { meta as meta_freshrss } from "./freshrss/meta";
import { generate as generate_freshrss } from "./freshrss";
import { meta as meta_ghost } from "./ghost/meta";
import { generate as generate_ghost } from "./ghost";
import { meta as meta_gitea } from "./gitea/meta";
import { generate as generate_gitea } from "./gitea";
import { meta as meta_gotify } from "./gotify/meta";
import { generate as generate_gotify } from "./gotify";
import { meta as meta_hastebin } from "./hastebin/meta";
import { generate as generate_hastebin } from "./hastebin";
import { meta as meta_hastypaste } from "./hastypaste/meta";
import { generate as generate_hastypaste } from "./hastypaste";
import { meta as meta_hedgedoc } from "./hedgedoc/meta";
import { generate as generate_hedgedoc } from "./hedgedoc";
import { meta as meta_heimdall } from "./heimdall/meta";
import { generate as generate_heimdall } from "./heimdall";
import { meta as meta_homarr } from "./homarr/meta";
import { generate as generate_homarr } from "./homarr";
import { meta as meta_homeassistant } from "./homeassistant/meta";
import { generate as generate_homeassistant } from "./homeassistant";
import { meta as meta_imgproxy } from "./imgproxy/meta";
import { generate as generate_imgproxy } from "./imgproxy";
import { meta as meta_jellyfin } from "./jellyfin/meta";
import { generate as generate_jellyfin } from "./jellyfin";
import { meta as meta_jellyseerr } from "./jellyseerr/meta";
import { generate as generate_jellyseerr } from "./jellyseerr";
import { meta as meta_jirafeau } from "./jirafeau/meta";
import { generate as generate_jirafeau } from "./jirafeau";
import { meta as meta_kanboard } from "./kanboard/meta";
import { generate as generate_kanboard } from "./kanboard";
import { meta as meta_kavita } from "./kavita/meta";
import { generate as generate_kavita } from "./kavita";
import { meta as meta_komga } from "./komga/meta";
import { generate as generate_komga } from "./komga";
import { meta as meta_lavalink } from "./lavalink/meta";
import { generate as generate_lavalink } from "./lavalink";
import { meta as meta_lenpaste } from "./lenpaste/meta";
import { generate as generate_lenpaste } from "./lenpaste";
import { meta as meta_libreoffice } from "./libreoffice/meta";
import { generate as generate_libreoffice } from "./libreoffice";
import { meta as meta_libretranslate } from "./libretranslate/meta";
import { generate as generate_libretranslate } from "./libretranslate";
import { meta as meta_lychee } from "./lychee/meta";
import { generate as generate_lychee } from "./lychee";
import { meta as meta_mailcrab } from "./mailcrab/meta";
import { generate as generate_mailcrab } from "./mailcrab";
import { meta as meta_mailhog } from "./mailhog/meta";
import { generate as generate_mailhog } from "./mailhog";
import { meta as meta_matomo } from "./matomo/meta";
import { generate as generate_matomo } from "./matomo";
import { meta as meta_mattermost } from "./mattermost/meta";
import { generate as generate_mattermost } from "./mattermost";
import { meta as meta_mealie } from "./mealie/meta";
import { generate as generate_mealie } from "./mealie";
import { meta as meta_meilisearch } from "./meilisearch/meta";
import { generate as generate_meilisearch } from "./meilisearch";
import { meta as meta_memos } from "./memos/meta";
import { generate as generate_memos } from "./memos";
import { meta as meta_metabase } from "./metabase/meta";
import { generate as generate_metabase } from "./metabase";
import { meta as meta_metube } from "./metube/meta";
import { generate as generate_metube } from "./metube";
import { meta as meta_miniflux } from "./miniflux/meta";
import { generate as generate_miniflux } from "./miniflux";
import { meta as meta_mysql_backup } from "./mysql-backup/meta";
import { generate as generate_mysql_backup } from "./mysql-backup";
import { meta as meta_n_8_n } from "./n8n/meta";
import { generate as generate_n_8_n } from "./n8n";
import { meta as meta_nextcloud } from "./nextcloud/meta";
import { generate as generate_nextcloud } from "./nextcloud";
import { meta as meta_nodered } from "./nodered/meta";
import { generate as generate_nodered } from "./nodered";
import { meta as meta_ntfy } from "./ntfy/meta";
import { generate as generate_ntfy } from "./ntfy";
import { meta as meta_nzbget } from "./nzbget/meta";
import { generate as generate_nzbget } from "./nzbget";
import { meta as meta_openspeedtest } from "./openspeedtest/meta";
import { generate as generate_openspeedtest } from "./openspeedtest";
import { meta as meta_paperlessngx } from "./paperlessngx/meta";
import { generate as generate_paperlessngx } from "./paperlessngx";
import { meta as meta_phpmyadmin } from "./phpmyadmin/meta";
import { generate as generate_phpmyadmin } from "./phpmyadmin";
import { meta as meta_pidgin } from "./pidgin/meta";
import { generate as generate_pidgin } from "./pidgin";
import { meta as meta_plex } from "./plex/meta";
import { generate as generate_plex } from "./plex";
import { meta as meta_pocketbase } from "./pocketbase/meta";
import { generate as generate_pocketbase } from "./pocketbase";
import { meta as meta_portainer } from "./portainer/meta";
import { generate as generate_portainer } from "./portainer";
import { meta as meta_postgres_backup } from "./postgres-backup/meta";
import { generate as generate_postgres_backup } from "./postgres-backup";
import { meta as meta_powerdns_admin } from "./powerdns-admin/meta";
import { generate as generate_powerdns_admin } from "./powerdns-admin";
import { meta as meta_prowlarr } from "./prowlarr/meta";
import { generate as generate_prowlarr } from "./prowlarr";
import { meta as meta_psitransfer } from "./psitransfer/meta";
import { generate as generate_psitransfer } from "./psitransfer";
import { meta as meta_rabbitmq } from "./rabbitmq/meta";
import { generate as generate_rabbitmq } from "./rabbitmq";
import { meta as meta_radarr } from "./radarr/meta";
import { generate as generate_radarr } from "./radarr";
import { meta as meta_registry } from "./registry/meta";
import { generate as generate_registry } from "./registry";
import { meta as meta_remmina } from "./remmina/meta";
import { generate as generate_remmina } from "./remmina";
import { meta as meta_restreamer } from "./restreamer/meta";
import { generate as generate_restreamer } from "./restreamer";
import { meta as meta_rocketchat } from "./rocketchat/meta";
import { generate as generate_rocketchat } from "./rocketchat";
import { meta as meta_simpletorrent } from "./simpletorrent/meta";
import { generate as generate_simpletorrent } from "./simpletorrent";
import { meta as meta_soketi } from "./soketi/meta";
import { generate as generate_soketi } from "./soketi";
import { meta as meta_sonarr } from "./sonarr/meta";
import { generate as generate_sonarr } from "./sonarr";
import { meta as meta_sshwifty } from "./sshwifty/meta";
import { generate as generate_sshwifty } from "./sshwifty";
import { meta as meta_statping_ng } from "./statping-ng/meta";
import { generate as generate_statping_ng } from "./statping-ng";
import { meta as meta_strapi } from "./strapi/meta";
import { generate as generate_strapi } from "./strapi";
import { meta as meta_umami } from "./umami/meta";
import { generate as generate_umami } from "./umami";
import { meta as meta_uptimekuma } from "./uptimekuma/meta";
import { generate as generate_uptimekuma } from "./uptimekuma";
import { meta as meta_vaultwarden } from "./vaultwarden/meta";
import { generate as generate_vaultwarden } from "./vaultwarden";
import { meta as meta_verdaccio } from "./verdaccio/meta";
import { generate as generate_verdaccio } from "./verdaccio";
import { meta as meta_vscode_server } from "./vscode-server/meta";
import { generate as generate_vscode_server } from "./vscode-server";
import { meta as meta_weblate } from "./weblate/meta";
import { generate as generate_weblate } from "./weblate";
import { meta as meta_wg_easy } from "./wg-easy/meta";
import { generate as generate_wg_easy } from "./wg-easy";
import { meta as meta_whiteboard } from "./whiteboard/meta";
import { generate as generate_whiteboard } from "./whiteboard";
import { meta as meta_wikijs } from "./wikijs/meta";
import { generate as generate_wikijs } from "./wikijs";
import { meta as meta_wordpress } from "./wordpress/meta";
import { generate as generate_wordpress } from "./wordpress";

const templates = [
  { slug: "ackee", meta: meta_ackee, generate: generate_ackee },
  { slug: "adminer", meta: meta_adminer, generate: generate_adminer },
  { slug: "anonupload", meta: meta_anonupload, generate: generate_anonupload },
  { slug: "appsmith", meta: meta_appsmith, generate: generate_appsmith },
  { slug: "baserow", meta: meta_baserow, generate: generate_baserow },
  { slug: "bookstack", meta: meta_bookstack, generate: generate_bookstack },
  { slug: "budibase", meta: meta_budibase, generate: generate_budibase },
  { slug: "changedetection", meta: meta_changedetection, generate: generate_changedetection },
  { slug: "dashy", meta: meta_dashy, generate: generate_dashy },
  { slug: "directus", meta: meta_directus, generate: generate_directus },
  { slug: "domainmod", meta: meta_domainmod, generate: generate_domainmod },
  { slug: "drone-runner", meta: meta_drone_runner, generate: generate_drone_runner },
  { slug: "drone", meta: meta_drone, generate: generate_drone },
  { slug: "duplicati", meta: meta_duplicati, generate: generate_duplicati },
  { slug: "element", meta: meta_element, generate: generate_element },
  { slug: "emby", meta: meta_emby, generate: generate_emby },
  { slug: "fider", meta: meta_fider, generate: generate_fider },
  { slug: "filebrowser", meta: meta_filebrowser, generate: generate_filebrowser },
  { slug: "filezilla", meta: meta_filezilla, generate: generate_filezilla },
  { slug: "firefox", meta: meta_firefox, generate: generate_firefox },
  { slug: "flame", meta: meta_flame, generate: generate_flame },
  { slug: "flarum", meta: meta_flarum, generate: generate_flarum },
  { slug: "freshrss", meta: meta_freshrss, generate: generate_freshrss },
  { slug: "ghost", meta: meta_ghost, generate: generate_ghost },
  { slug: "gitea", meta: meta_gitea, generate: generate_gitea },
  { slug: "gotify", meta: meta_gotify, generate: generate_gotify },
  { slug: "hastebin", meta: meta_hastebin, generate: generate_hastebin },
  { slug: "hastypaste", meta: meta_hastypaste, generate: generate_hastypaste },
  { slug: "hedgedoc", meta: meta_hedgedoc, generate: generate_hedgedoc },
  { slug: "heimdall", meta: meta_heimdall, generate: generate_heimdall },
  { slug: "homarr", meta: meta_homarr, generate: generate_homarr },
  { slug: "homeassistant", meta: meta_homeassistant, generate: generate_homeassistant },
  { slug: "imgproxy", meta: meta_imgproxy, generate: generate_imgproxy },
  { slug: "jellyfin", meta: meta_jellyfin, generate: generate_jellyfin },
  { slug: "jellyseerr", meta: meta_jellyseerr, generate: generate_jellyseerr },
  { slug: "jirafeau", meta: meta_jirafeau, generate: generate_jirafeau },
  { slug: "kanboard", meta: meta_kanboard, generate: generate_kanboard },
  { slug: "kavita", meta: meta_kavita, generate: generate_kavita },
  { slug: "komga", meta: meta_komga, generate: generate_komga },
  { slug: "lavalink", meta: meta_lavalink, generate: generate_lavalink },
  { slug: "lenpaste", meta: meta_lenpaste, generate: generate_lenpaste },
  { slug: "libreoffice", meta: meta_libreoffice, generate: generate_libreoffice },
  { slug: "libretranslate", meta: meta_libretranslate, generate: generate_libretranslate },
  { slug: "lychee", meta: meta_lychee, generate: generate_lychee },
  { slug: "mailcrab", meta: meta_mailcrab, generate: generate_mailcrab },
  { slug: "mailhog", meta: meta_mailhog, generate: generate_mailhog },
  { slug: "matomo", meta: meta_matomo, generate: generate_matomo },
  { slug: "mattermost", meta: meta_mattermost, generate: generate_mattermost },
  { slug: "mealie", meta: meta_mealie, generate: generate_mealie },
  { slug: "meilisearch", meta: meta_meilisearch, generate: generate_meilisearch },
  { slug: "memos", meta: meta_memos, generate: generate_memos },
  { slug: "metabase", meta: meta_metabase, generate: generate_metabase },
  { slug: "metube", meta: meta_metube, generate: generate_metube },
  { slug: "miniflux", meta: meta_miniflux, generate: generate_miniflux },
  { slug: "mysql-backup", meta: meta_mysql_backup, generate: generate_mysql_backup },
  { slug: "n8n", meta: meta_n_8_n, generate: generate_n_8_n },
  { slug: "nextcloud", meta: meta_nextcloud, generate: generate_nextcloud },
  { slug: "nodered", meta: meta_nodered, generate: generate_nodered },
  { slug: "ntfy", meta: meta_ntfy, generate: generate_ntfy },
  { slug: "nzbget", meta: meta_nzbget, generate: generate_nzbget },
  { slug: "openspeedtest", meta: meta_openspeedtest, generate: generate_openspeedtest },
  { slug: "paperlessngx", meta: meta_paperlessngx, generate: generate_paperlessngx },
  { slug: "phpmyadmin", meta: meta_phpmyadmin, generate: generate_phpmyadmin },
  { slug: "pidgin", meta: meta_pidgin, generate: generate_pidgin },
  { slug: "plex", meta: meta_plex, generate: generate_plex },
  { slug: "pocketbase", meta: meta_pocketbase, generate: generate_pocketbase },
  { slug: "portainer", meta: meta_portainer, generate: generate_portainer },
  { slug: "postgres-backup", meta: meta_postgres_backup, generate: generate_postgres_backup },
  { slug: "powerdns-admin", meta: meta_powerdns_admin, generate: generate_powerdns_admin },
  { slug: "prowlarr", meta: meta_prowlarr, generate: generate_prowlarr },
  { slug: "psitransfer", meta: meta_psitransfer, generate: generate_psitransfer },
  { slug: "rabbitmq", meta: meta_rabbitmq, generate: generate_rabbitmq },
  { slug: "radarr", meta: meta_radarr, generate: generate_radarr },
  { slug: "registry", meta: meta_registry, generate: generate_registry },
  { slug: "remmina", meta: meta_remmina, generate: generate_remmina },
  { slug: "restreamer", meta: meta_restreamer, generate: generate_restreamer },
  { slug: "rocketchat", meta: meta_rocketchat, generate: generate_rocketchat },
  { slug: "simpletorrent", meta: meta_simpletorrent, generate: generate_simpletorrent },
  { slug: "soketi", meta: meta_soketi, generate: generate_soketi },
  { slug: "sonarr", meta: meta_sonarr, generate: generate_sonarr },
  { slug: "sshwifty", meta: meta_sshwifty, generate: generate_sshwifty },
  { slug: "statping-ng", meta: meta_statping_ng, generate: generate_statping_ng },
  { slug: "strapi", meta: meta_strapi, generate: generate_strapi },
  { slug: "umami", meta: meta_umami, generate: generate_umami },
  { slug: "uptimekuma", meta: meta_uptimekuma, generate: generate_uptimekuma },
  { slug: "vaultwarden", meta: meta_vaultwarden, generate: generate_vaultwarden },
  { slug: "verdaccio", meta: meta_verdaccio, generate: generate_verdaccio },
  { slug: "vscode-server", meta: meta_vscode_server, generate: generate_vscode_server },
  { slug: "weblate", meta: meta_weblate, generate: generate_weblate },
  { slug: "wg-easy", meta: meta_wg_easy, generate: generate_wg_easy },
  { slug: "whiteboard", meta: meta_whiteboard, generate: generate_whiteboard },
  { slug: "wikijs", meta: meta_wikijs, generate: generate_wikijs },
  { slug: "wordpress", meta: meta_wordpress, generate: generate_wordpress },
];

export default templates;
